// Generates src/schema.d.ts from the committed backend OpenAPI document
// (apps/api/openapi.json, produced by `make openapi`). CI fails if the output drifts.
import { existsSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const specPath = resolve(pkgRoot, "../../apps/api/openapi.json");
const outPath = resolve(pkgRoot, "src/schema.d.ts");

if (!existsSync(specPath)) {
  console.error(`api-client: ${specPath} is missing, run \`make openapi\` first`);
  process.exit(1);
}

const ast = await openapiTS(pathToFileURL(specPath));
const header =
  "/**\n * This file is generated by scripts/generate.mjs (openapi-typescript).\n * Do not edit by hand; run `pnpm api-client:generate`.\n */\n\n";
writeFileSync(outPath, header + astToString(ast));
console.log("api-client: generated src/schema.d.ts from apps/api/openapi.json");
